apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-config-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/schalla7/schalk-argo-config.git
    targetRevision: HEAD
    path: helm/templates
    
  destination:
    namespace: schalk-prod
    server: https://kubernetes.default.svc
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
