apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-config-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm
    repoURL: https://github.com/schalla7/schalk-argo-config
    targetRevision: HEAD
    
  destination:
    namespace: schalk-prod
    server: https://kubernetes.default.svc
  
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
