# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: schalk
type: Opaque
data:
  mongo-user: bXlVc2VyTmFtZUhlcmU=
  mongo-password: bXlNb25nb1dhZ1dvb3Jk
  # Example:
  # password: {{ .Values.password | b64enc }}
# stringData:
#   username: admin      # required field for kubernetes.io/basic-auth
#   password: t0p-Secret # required field for kubernetes.io/basic-auth
# immutable: true
